matrix:
  include:
    - language: cpp
      script:
        - ./test/build.sh
    - language: python
      python: 2.7
      cache:
        directories:
          - "~/.platformio"
      install:
        - pip install -U platformio
      script:
        - platformio run -v